### ISSUE TITLE
Not able to run action server

### ISSUE THREAD

**Issue by iamabhishekchakraborty** [samik-saha/rasa-chatbot#2]
Thanks a ton for this beautiful code repo which has made life easier by multiple folds. Everything from the repo works perfectly fine and I have been able successfully replicate it for my use-case - but facing a problem while running the rasa model.
While I invoke the dockerfile which runs the rasa model and also the rasa action server in background I am getting the error message that -

> 2020-02-11 13:21:22 INFO     rasa_sdk.endpoint  - Starting action endpoint server...
> 2020-02-11 13:21:22 ERROR    rasa_sdk.executor  - Failed to register package 'app.actions'.
> Traceback (most recent call last):
>   File "/build/lib/python3.6/site-packages/rasa_sdk/executor.py", line 206, in register_package
>     self._import_submodules(package)
>   File "/build/lib/python3.6/site-packages/rasa_sdk/executor.py", line 191, in _import_submodules
>     package = importlib.import_module(package)
>   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
> ModuleNotFoundError: No module named 'app'
> 2020-02-11 13:21:23 INFO     root  - Starting Rasa server on http://localhost:5005
> 2020-02-11 13:21:30.621038: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)

As you could see the rasa server is successfully up and totally interact-able but not the action server. Am I missing something here? Thanks in advance.

**Comment by iamabhishekchakraborty** [comment]
Fixed this by a small change in the "start_services.sh" script.
